language: go

go:
  - master

# Yes email me the results of the test runs.
notifications:
  email: true

before_script:
  - GO_FILES=$(find . -iname '*.go' -type f | grep -v /examples/) # All the .go files, excluding examples
  - go get github.com/golang/lint/golint       # Linter

script:
  - go test -v ./...                   # Run all the tests with the race detector enabled
  - go vet ./...                               # go vet is the official Go static analyzer
  - golint -set_exit_status $(go list ./...) # one last linter
  - go test -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)